# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main", "initial" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Publish to private nuget repo
      run: |
        dotnet nuget list source
        dotnet nuget add source ${{ secrets.NUGET_FEED_URL }} -u "-" -p ${{ secrets.TSP_NUGET_PAT }} --store-password-in-clear-text --valid-authentication-types "basic" 
        dotnet nuget push "Tilde.Translation/bin/Release/Tilde.Translation.*.nupkg" --source ${{ secrets.NUGET_FEED_URL }} --api-key VSTS
